### ISSUE TITLE
Ruby Capstone Kanban Board Setup

### ISSUE THREAD

**Issue by IsmaelMastronardi** [ivangonzalez224/Catalog-of-my-things#27]
## There are 3 people on the team : 
- @IsmaelMastronardi. Team member 1
- @ivangonzalez224. Team member 2
- @hajnaloltyan. Team member 3
## Link to the project : 
https://github.com/ivangonzalez224/Catalog-of-my-things/projects/1

**Comment by tresorsawasawa** [comment]
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @IsmaelMastronardi, @hajnaloltyan, and @ivangonzalez224 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All requirements have specific card :heavy_check_mark: 
- Cards have descriptive tittle :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] As required for the project, kindly ensure that each card on the board has a description of the task as some of them don't have description of the task. **I recommend you to recheck all your cards and add description for those that don't have.**.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Munsa1** [comment]
Hi @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Changes :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
